### ISSUE TITLE
video image freezes

### ISSUE THREAD

**Issue by andy1wes** [Fugiman/google-meet-grid-view#113]
**Describe what is broken**
On Mac running High Sierra, following the most recent security update, the video feed from laptop camera will freeze.  Display from other participants works, but they report my feed is frozen. Starting another app like Photo Booth confirms the camera is still working.  Often have to force-quit Chrome to get out of it.

**Expected behavior**
The video feed would work.

**Screenshots**
I have a screencastify video of the problem, and a HAR file.

**Software used:**
 - High Sierra
 - Chrome

**Additional context**

**Comment by Fugiman** [comment]
Does disabling Grid View fix the issue? The grid view extension does not modify the camera or your upload to Google in any way and should not be the cause of this issue. If you're able to demonstrate that the issue only occurs when Grid View is enabled I can look into it, but otherwise I can't help with issues caused by the native Google Meet app.

**Comment by andy1wes** [comment]
Thanks for getting back to me. I was able to reproduce the problem with grid view disabled. I’ve submitted the issue to google.

On May 9, 2020, at 04:48, Fugi <notifications@github.com> wrote:

﻿

Does disabling Grid View fix the issue? The grid view extension does not modify the camera or your upload to Google in any way and should not be the cause of this issue. If you're able to demonstrate that the issue only occurs when Grid View is enabled I can look into it, but otherwise I can't help with issues caused by the native Google Meet app.
