### ISSUE TITLE
a vista em grelha deixou de funcionar há 2 dias e eu não consigo resolver o problema. 

### ISSUE THREAD

**Issue by rosariosalsa** [Fugiman/google-meet-grid-view#156]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by Fugiman** [comment]
On May 22nd around 1pm (US Pacific Time) Google updated Meet in a way that broke Grid View, resulting in users seeing a list rather than a grid. I released v1.31 that was intended to fix Grid View to work with the new Meet code.

For some users this fix did not work. As of May 25th, 6am (US Pacific Time) I've released v1.32 which should fix the issue for all remaining users.

You can find the working version at the following links:
Chrome: https://chrome.google.com/webstore/detail/google-meet-grid-view/kklailfgofogmmdlhgmjgenehkjoioip
Firefox: https://addons.mozilla.org/en-US/firefox/addon/google-meet-gridview

**Please also make sure you do not have any other grid view extensions installed.** You can check this at chrome://extensions and can remove any duplicates with the "remove" button. If you're unsure, remove them all and then reinstall the extension from the link above.
