### ISSUE TITLE
It does not seem as though anything has downloaded or changed to allow a gridview with google meets thru Chrome. 

### ISSUE THREAD

**Issue by lucindarudolph** [Fugiman/google-meet-grid-view#160]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by Eagle-Man** [comment]
@lucindarudolph Could you try filling out the form properly?  That would be more helpful in diagnosing the problem.

**Comment by lucindarudolph** [comment]
Gosh- even that is confusing.. sorry

Lucinda Rudolph
Visual Arts Teacher
Rolling Hills Prep School prides itself on being a forward-looking,
academically rigorous college-prep school with a soul.
Renaissance School believes that bright students who learn differently
can rise to great heights when they become empowered and confident.
One Rolling Hills Prep Way <x-apple-data-detectors://9/0> |<x-apple-data-detectors://9/0> San Pedro, CA 90732<x-apple-data-detectors://9/0>
P: (310) 791-1101<tel:(310)%20791-1101>
lrudolph@rollinghillsprep.org

On May 27, 2020, at 10:45 AM, Eagle-Man <notifications@github.com> wrote:

﻿

@lucindarudolph<https://github.com/lucindarudolph> Could you try filling out the form properly? That would be more helpful in diagnosing the problem.

**Comment by Mrs-Sanborn** [comment]
I need grid working properly by 1:15 PT to hold my LAST meeting with my kids for the year.

**Comment by Eagle-Man** [comment]
@Mrs-Sanborn That is not helpful in solving the problem.  Can you please fill out the information at the top so that the creators can determine the issue?

**Comment by Fugiman** [comment]
I'm closing this because there was no actionable information provided. The form is critical to me being able to help you, saying "it's not working" tells me nothing.

Ensure you've installed the official extension: https://chrome.google.com/webstore/detail/google-meet-grid-view/kklailfgofogmmdlhgmjgenehkjoioip

Ensure you do not have any other grid extensions installed at chrome://extensions

If you get a 404 from Google visiting the Chrome link, please clear your cookies and reload the page.

If you get "blocked by administrator" contact your IT department.
