### ISSUE TITLE
v1.35.0 of google-meet-grid-view

### ISSUE THREAD

**Issue by koonpb** [Fugiman/google-meet-grid-view#193]
Video images in grid view freeze frequently in ver v1.35.0 of google meet grid view. The freeze will last for about a minute or so then recover by itself. 

Previous version of the grid view extension does not have this problem.

Software used:
OS: Windows10
Browser : Chrome Version 83.0.4103.97 (Official Build) (64-bit)

Any help will be appreciated.  Thank you very very much

**Comment by FugiTech** [comment]
On June 14th Google updated Meet with changes to the Tiled view, breaking the Grid View extension. I quickly diagnosed the issue and released a fix as v1.36. However I did not test this fix in a large meeting, which led to browsers hanging or crashing for many users in meetings over 16 people. This was caused by the google code assuming a maximum of 16 videos and entering an infinite loop. I'm extremely sorry I did not test this change thoroughly enough to discover this issue before releasing v1.36.

As of now I am releasing v1.37 which properly fixes the issue. I would like to thank @rogerl19 and his coworkers for hosting a meeting in which I could test this change. In addition to fixing the crash and restoring the expected functionality, it also will automatically lower video quality in large meetings to try and avoid the freezing some users have reported. If the automatic quality is not to your liking, you can override it in the Advanced Settings.

Please note that versions must be reviewed by Google and I do not control how long it takes. **Until the review is complete you can fix the issue by setting your meet layout to Sidebar.** Thanks to @ivanmalgra for finding this fix.

Once again I apologize for the issues caused by my extension, and will endeavor to do better in the future. If you have issues with v1.37 please comment in #225
