### ISSUE TITLE
GOOGLE MEET GRID VIEW NO FUNCIONA

### ISSUE THREAD

**Issue by kchopy** [Fugiman/google-meet-grid-view#210]
Corrimos en 3 pc y no funcionaba bien.. Salia una columna de usuarios pero no en cuadricula.
Desinstalamos y volvimos a instalar y el problema continuaba.. 15/06/2020

**Comment by anne-nelson** [comment]
Duplicado de #202, por favor revise los problemas abiertos antes de crear uno nuevo

**Comment by jctovilla** [comment]
The same problem 

![image](https://user-images.githubusercontent.com/1221090/84685469-f8a9ea00-aeff-11ea-9db9-6d813a34b47b.png)

**Comment by klauriens** [comment]
same error

**Comment by amitkbhola** [comment]
Its broken I think we sould commit the old version 1.34

**Comment by karledurante** [comment]
same here.

**Comment by sailorotelo** [comment]
I have the same problem, I uninstalled and reinstalled but it's not work, please fix the bug.

Thanks in advance.

**Comment by anne-nelson** [comment]
@klauriens @amitkbhola @karledurante @sailorotelo If you are also having the same issue the best thing to do is to +1 the original post, adding comments just to say "me too" just spams the creator and doesn't bring anything to this post.

This issue is also a duplicate of #202, you should look there for updates.

**Comment by Fugiman** [comment]
(Maybe) fixed in v1.36, please update.
