### ISSUE TITLE
Version 1.36 is still not working. 

### ISSUE THREAD

**Issue by Yukeechan** [Fugiman/google-meet-grid-view#214]
Thank you Fugi for working our version 1.36, just installed in but still not working. This is the picture we have when we use Google Grid View. and worse still, the page will be unresponsive once we clicked on the Google Grid View version 1.36. Appreciate if you could help because our school relies on your App heavily to monitor our students  during assessments. Thank you.

![image](https://user-images.githubusercontent.com/65798091/84734571-d2ee1500-afd3-11ea-82f0-0760ab285720.png)

![image](https://user-images.githubusercontent.com/65798091/84734804-75a69380-afd4-11ea-9fef-c05646295b4a.png)

**Comment by dmuns-mda** [comment]
Good morning,

With version 1.36.0 the problems persist :'(

![image](https://user-images.githubusercontent.com/66991656/84741685-b6d87c80-afaf-11ea-813b-b5ccbc76274f.png)

**Comment by Pieter-N** [comment]
Same here unfortunately. Version 1.36 with Chrome 83.0.4103.97.
Three crashes in a 10 minute meeting. Page unresponsive.

**Comment by Seegras** [comment]
Same here on Chrome 83.0.4103.97 (Official Build) (64-bit) on Linux. Page freezes, sound works a few minutes longer, then Chrome asks me whether I want to stop unresponsive scripts. If I let them run, nothing happens anymore; if I quit them, I get thrown out.

**Comment by Diegovano** [comment]
I am also having similar issues with Firefox Developer Edition 78.0b7

**Comment by 0bmxa** [comment]
to quote [@tankrizzo on #202](https://github.com/Fugiman/google-meet-grid-view/issues/202#issuecomment-644035413)
>Please stop commenting that this is broken or "same issue". Give a +1 to the original issue. This is not Facebook.

**Comment by Diegovano** [comment]
Well the difference is that #202 has to do with version 1.35.0, whereas this is about 1.36.0.
Furthermore, #202 doesn't mention full on browser crashes.

**Comment by EnzoLiv** [comment]
The grid work fine with less than 16 people. When pass more than 16, the page freezes and crash.

**Comment by benp** [comment]
I'm seeing this in the Extensions panel, if that can be of any help
![Image 2020-06-16 at 09 47 13](https://user-images.githubusercontent.com/62801/84783072-d030f700-afb6-11ea-808c-8826618e2b45.png)

**Comment by ivanmalgra** [comment]
resuelto.
https://github.com/Fugiman/google-meet-grid-view/issues/223

**Comment by FugiTech** [comment]
On June 14th Google updated Meet with changes to the Tiled view, breaking the Grid View extension. I quickly diagnosed the issue and released a fix as v1.36. However I did not test this fix in a large meeting, which led to browsers hanging or crashing for many users in meetings over 16 people. This was caused by the google code assuming a maximum of 16 videos and entering an infinite loop. I'm extremely sorry I did not test this change thoroughly enough to discover this issue before releasing v1.36.

As of now I am releasing v1.37 which properly fixes the issue. I would like to thank @rogerl19 and his coworkers for hosting a meeting in which I could test this change. In addition to fixing the crash and restoring the expected functionality, it also will automatically lower video quality in large meetings to try and avoid the freezing some users have reported. If the automatic quality is not to your liking, you can override it in the Advanced Settings.

Please note that versions must be reviewed by Google and I do not control how long it takes. **Until the review is complete you can fix the issue by setting your meet layout to Sidebar.** Thanks to @ivanmalgra for finding this fix.

Once again I apologize for the issues caused by my extension, and will endeavor to do better in the future. If you have issues with v1.37 please comment in #225
