### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by jan-xyz** [Fugiman/google-meet-grid-view#28]
I installed it with Tampermonkey on Safari but couldn't get it to show up the button.

Is there a way I can help with debugging this?

Safari Version 13.1 (15609.1.20.111.8)
MacOS Catalin 10.15.4

**Comment by Fugiman** [comment]
Tampermonkey for Safari costs money so I was unable to test it directly, but having run the script on Safari it seems like CSS grids are not supported properly in Safari. Unfortunately this means this script won't ever work in Safari and you'll need to use a different browser if you want to use it. Sorry.

Both Firefox and Chrome have been tested and are supported.

**Comment by jan-xyz** [comment]
Thanks for the quick reply!

I would totally be willing to pay for your Tampermonkey copy and/or donate something to get this going or enable you to try it out if you want to.

This is in no way meant to persuade you into doing it, it's just an offer 🙂

**Comment by Fugiman** [comment]
While I appreciate the offer the CSS I use simply doesn't work as expected with Safari, so even if I figured out why it wasn't working in Safari's Tampermonkey it still wouldn't do what you expect. It'd take a decent amount of effort to get it working and I simply don't have the time for such an overhaul at this time.

**Comment by Fugiman** [comment]
Another user reported Safari not working and I had time, so I bought Tampermonkey to figure out what was going on. Turns out Tampermonkey on Safari can't inject scripts into pages with strict CSP rules, as Safari doesn't follow the CSP spec in that regard. See the comment by the author of Tampermonkey [here](https://github.com/Tampermonkey/tampermonkey/issues/296#issuecomment-222356524)

Unfortunately that means that unless Tampermonkey or Safari address the issue there's nothing I can do to make the user script work on Safari. The only alternative would be to release a Safari extension, but I'm unsure how difficult that is and I'd still need to hack around the grid CSS not working. At this time I have no intention of releasing a Safari extension.

I'll update the README with this information so others aren't caught by surprise.
