### ISSUE TITLE
Feature request: Hide the 'Pin/Mute' widget that appears in the center of each video

### ISSUE THREAD

**Issue by iampegram** [Fugiman/google-meet-grid-view#33]
It can be visually distracting to have that pop up over each video as you use your mouse, and in my opinion, it's not necessary when the point of the plugin is to have everyone onscreen at the same time. Great work, by the way. I've looked at the obfuscated javascript files, it's amazing you were able to comprehend what was going on..

**Comment by Fugiman** [comment]
Thanks! It wasn't easy to decipher but it was a fun puzzle :)

The Pin & Mute overlay on hover is a built-in feature of Google Meets and I'm not willing to remove or hide any native features as that tends to be confusing to users and can cause bad will with Google. Please note that Pinning _does_ work with the script and will make the pinned video take up 1/4th of the screen so that it is larger but other participants are still visible. This is useful if there's a primary speaker you want to pay attention to. Muting works as normal.
