### ISSUE TITLE
No longer showing more than 5 attendees

### ISSUE THREAD

**Issue by JulianMaartens** [Fugiman/google-meet-grid-view#50]
Hi,

Although the extension worked earlier, we're currently not able to see more than 5 attendees at the same time. Looking at the other reviews in the Chrome Web Store (https://chrome.google.com/webstore/detail/google-meet-grid-view/bjkegbgpfgpikgkfidhcihhiflbjgfic/reviews)

We deployed the extension through G-Suite, earlier versions worked just fine.
Apologies if this has been posted before.

**Comment by Fugiman** [comment]
Google updated Meets and broke the extension. It is fixed in v1.18 which is available as a user script via greasyfork. The official extension (https://chrome.google.com/webstore/detail/kklailfgofogmmdlhgmjgenehkjoioip) is under review and I'm unsure when it'll be released. The extension you linked is not operated nor supported by me.

**Comment by JulianMaartens** [comment]
Apologies, linked to the wrong extension. But I'll await the approved version then. Thanks!
