### ISSUE TITLE
Show yourself in grid does not work

### ISSUE THREAD

**Issue by maxvisser** [Fugiman/google-meet-grid-view#51]
I am not sure on how it suposes to work but on Brave it does not work (does nothing)

**Comment by Nino-Dioses** [comment]
Reporting the same behaviour in Chrome
Since today (i think) following behaviour has changed:
- Show yourself doesn't work
- According to the layout chosen on google meet ( settings -> change layout -> [select layout]), the grid behaves differently, or doesn't show all participants
- Grid position of participants changes all the time, depending of who is talking in that moment

**Comment by adr29truck** [comment]
What version of the extension do you use?
Asking since google released an update that appear to have broken this functionality.
Running the latest version of the extension ```1.18``` seems to resolve this.

**Comment by Nino-Dioses** [comment]
In chrome extensions i have the following information
Version
2020.4.12

**Comment by adr29truck** [comment]
Try the latest version by installing it from: [https://greasyfork.org/en/scripts/397862-google-meet-grid-view](https://greasyfork.org/en/scripts/397862-google-meet-grid-view)
The updates have not been pushed out to the stores yet.

**Comment by Nino-Dioses** [comment]
It just got to the Chrome Store, I can confirm that version Version 2020.4.15 fixes the problem. Thanks a lot!

**Comment by maxvisser** [comment]
I am not sure on how to install it from greasyfork. I will close this issue as it seems to be fixed in an upcoming release.
