### ISSUE TITLE
grid only showing 6 students at a time

### ISSUE THREAD

**Issue by DliteDK** [Fugiman/google-meet-grid-view#54]
yesterday gridview showed all meet members but today it only shows 6

**Comment by adr29truck** [comment]
What version of the extension do you use?
Asking since google released an update that appear to have broken this functionality.
Running the latest version of the extension ```1.18``` seems to resolve this.

Try the latest version by installing it from: https://greasyfork.org/en/scripts/397862-google-meet-grid-view
The updates have not been pushed out to the stores yet.

**Comment by milliewong** [comment]
heads up that the google store ver. is still at 1.15 as of 11 AM est

**Comment by jyergatian** [comment]
I suspect the reason why the Chrome Web Store is not updating may be the manifest.json file. It hasn't been updated to the 1.18.0 version number. I've submitted a pull request #62 to fix this so @Fugiman can merge, pack, and re-upload to the Chrome Web Store.

**Comment by Fugiman** [comment]
Nah, it's because Google takes a week to review my updates for some reason :/

**Comment by Fugiman** [comment]
Closing as this was fixed in v1.18, despite the official chrome extension not working until Google accepts the new version.
