### ISSUE TITLE
[FEATURE REQUEST] Grid ordering

### ISSUE THREAD

**Issue by loretoparisi** [Fugiman/google-meet-grid-view#65]
Thank you for this amazing extension! Could be worth to add an ordering option, so that when new participants adds, the grid does not re-order by incoming users, while keep the grid ordered by name. In this way the position of each person will not change during the call :)

[UPDATE]
I can see that there is a `sort` in the code here

```javascript
// sort by participant name, or video id if the name is the same (when someone is presenting)
    ret.sort((a, b) => a[magicKey].name.localeCompare(b[magicKey].name) || a[magicKey].id.localeCompare(b[magicKey].id))
```

Not sure why when new participants are added a re-sort happens and they change positions. Maybe another option could be not only sorting by name, but in a FIFO ordering, so that each participant will just "keep" the initial position.

**Comment by revett** [comment]
IMO I'd prefer making sure that A-Z ordering stays consistent throughout a call.

**Comment by Fugiman** [comment]
People joining or leaving a call always has the potential to shift where participants are. Even if I do a FIFO ordering, it is possible that the grid resizes due to a participant joining which will move the videos. Ordering by name keeps the ordering fairly consistent and is the best default ordering I can think of. I'm not interested in adding multiple ordering options as that is more to maintain and more for users to think about.

**Comment by sebastienbarre** [comment]
Same here, an option to order by the time a person last joined instead of alphabetical would be useful. I understand situations may differ; in many of the meetings I'm in, people do not always arrive on time, at which point the ones who are late push other people around in the grid when they join. The scenario where people leave and come back (and therefore would disturb the grid anyway) happens a lot less often. Your mileage may vary of course.

Thanks! Great extension.
